# Generated by Django 5.0.3 on 2024-05-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='week06',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='이미지')),
                ('contentn', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(verbose_name='작성일')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
            ],
        ),
    ]
