# Generated by Django 5.0.5 on 2024-05-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_writer_alter_post_created_at_alter_post_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contentn',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='week06',
            old_name='contentn',
            new_name='content',
        ),
    ]
